### ISSUE TITLE
Stanford's CS107 is now restricted

### ISSUE THREAD

**Issue by aaronwinter** [prakhar1989/awesome-courses#122]
The link is dead. :skull:

**Comment by awelch83** [comment]
Then remove it and submit a pull request

Sent from my iPhone

On Jun 30, 2015, at 8:30, Aaron <notifications@github.com> wrote:

The link is dead.

**Comment by solveris** [comment]
https://courseware.stanford.edu/pg/courses/lectures/371747

**Comment by prakhar1989** [comment]
@solveris Updated the link. Thanks! :+1:
