### ISSUE TITLE
Fundamentals of Computer Networks CMU - link not working

### ISSUE THREAD

**Issue by bhalothia** [prakhar1989/awesome-courses#126]
http://www.ini740.com/F14/index.html is not accessible  - the correct link should be http://www.ini740.com/F15/index.html

**Comment by prakhar1989** [comment]
Fixed. Thanks :+1:

**Comment by bhalothia** [comment]
Oh I was about to send you a pull request. ;) Thanks!

**Comment by prakhar1989** [comment]
Haha! Next time you can beat me to it :wink:

**Comment by kazemihabib** [comment]
link is not accessible again - the correct link should be http://www.ini740.com/F17/

**Comment by qinhanlei** [comment]
Hi,
I suggest that just use link http://ini740.com .
It will redirect to newest index page, for now is http://www.ini740.com/F17/ .

**Comment by AbdelhakimTallab** [comment]
use the link http://www.ini740.rocks/F18/index.html. it's the working one now.
