### ISSUE TITLE
Add 10708 Probabilistic Graphical Models from CMU

### ISSUE THREAD

**Issue by mingloo** [prakhar1989/awesome-courses#130]
The course link is http://www.cs.cmu.edu/~epxing/Class/10708/lecture.html.

Lecture videos of PGM (Spring 2014) can be found [here](https://mediatech-stream.andrew.cmu.edu/Mediasite/Catalog/Full/33ec284c7d3b42bdaa51dd42deacb1e621).

**Comment by liquidmetal** [comment]
Merged in #180

**Comment by liquidmetal** [comment]
@mingloo did you already work through the assignments? Want to form a study group?

**Comment by awelch83** [comment]
Should this issue be marked "closed"?

**Comment by prakhar1989** [comment]
Closing this now. Thanks @awelch83!
