### ISSUE TITLE
Add video to Stanford CS231n

### ISSUE THREAD

**Issue by koallen** [prakhar1989/awesome-courses#160]
The videos are available online on YouTube. The link is [here](https://www.youtube.com/channel/UCPk8m_r6fkUSYmvgCBwq-sw/videos).

I think the course is not finished yet so new videos are keeping uploaded. Maybe you want to add the videos later when the course ends.

**Comment by prakhar1989** [comment]
This looks neat! You mind sending a pull request for this? Thanks =)

**Comment by koallen** [comment]
Just created the pull request!
