### ISSUE TITLE
Stanford cs108 doesn't have lecture video

### ISSUE THREAD

**Issue by zhongweiy** [prakhar1989/awesome-courses#164]
Hi, I can't find lecture video in cs108's course page: http://web.stanford.edu/class/cs108/. But there is a video icon in awesome-courses. Does I miss something?

**Comment by prakhar1989** [comment]
You're right. The videos for CS108 are not online. Thanks for letting me know - I'll update the readme file.

**Comment by raosid** [comment]
Was anyone able to find the lecture videos? Maybe an archive somewhere?

**Comment by kunge12345** [comment]
Hi, prakhar1989. Can you update the file? It took me so long and I didn't find any video...

**Comment by prakhar1989** [comment]
Hi, sorry for the confusion. I've removed the misleading video icon from CS 108. Thanks!
