### ISSUE TITLE
Make a new section for "Artificial Intelligence" courses.

### ISSUE THREAD

**Issue by ivmarkp** [prakhar1989/awesome-courses#168]
Hi,  there are currently 4 courses on Artificial Intelligence here. I feel the need to make a new section for it because personally, to find the related courses I had to search for each course individually and also other topics included in AI could also be put into this new section. Also, it will help contributors to add new AI courses quickly. What do you think? 

I've committed the required changes to the forked repo. I can send a pull request if it's not a bad idea.

**Comment by prakhar1989** [comment]
Sure .. sounds like a good idea. Send in a PR!

**Comment by ivmarkp** [comment]
Yes. Although, I think we can may be do the same thing for other sections as well such as Computer graphics(included with Computer vision courses too?), Computer Networks, Software Engineering etc. In fact, lot of courses in Misc section should be put into their appropriate sections if at least 3-4 courses belong to same section.

**Comment by prakhar1989** [comment]
Right. I think if there are >= 4 courses, we can assign a standalone section to it. If you're up to the task of doing the segregation and send in a PR, I'll be happy to merge those changes in :grinning:

**Comment by ivmarkp** [comment]
Sure. I'll do it for all the courses I am familiar with. :)
