### ISSUE TITLE
cs108 seems to be inaccessible now

### ISSUE THREAD

**Issue by elvis-sik** [prakhar1989/awesome-courses#232]
This is the link for convenience http://web.stanford.edu/class/cs108/

They seem to be using a new platform called `canvas` which requires priviledges to access.

**Comment by joelowj** [comment]
Hi @prakhar1989  This issue has been resolve, I suggest this issue to be closed.
Thanks a lot.

**Comment by prakhar1989** [comment]
Thanks @joelowj 👍
