### ISSUE TITLE
Expanding to all subjects

### ISSUE THREAD

**Issue by Bogidon** [prakhar1989/awesome-courses#262]
First, thank you all for this wonderful resource.

Now... it would be _awesome_ if the scope of this list could be broadened to include all MOOCs, not just those pertaining to Computer Science. For example, I am currently studying math, but outside of [rossant/awesome-math](https://github.com/rossant/awesome-math) (which is text focused) there's no open source list like this one. If you are open to this change, I volunteer to set us off in the new direction by curating the beginning of a section on math.

If you're not open to the change, it's fine (tho less awesome imo), but I would like to note that the name of this repo is misleading as it doesn't specify it's exclusive focus on CS. Another minor issue is that this focus is mentioned only in GitHub-specific data fields (headline and topics), and not in the README, making it difficult to tell if you're viewing the repo on anything other than GitHub (like if you cloned the repo locally).

**Comment by prakhar1989** [comment]
Hey thanks for checking this out! My background is in CS & I'm not sure if I'm eligible to judge courses (& their awesomeness) for other subjects. Having said that, I'll happy to link to your repo if you decide to build such a list. 😃 

> this repo is misleading as it doesn't specify it's exclusive focus on CS.

Thanks for bringing this up  - I'll make a change in the readme to reflect this better 👍
