### ISSUE TITLE
Point out if video lectures available

### ISSUE THREAD

**Issue by ahmetalpbalkan** [prakhar1989/awesome-courses#29]
Would be nice to point out which courses have videos and which ones don't from usability point of view. It's tedious to filter out the ones with video lectures.

**Comment by webfreee** [comment]
啥东东

**Comment by xu6148152** [comment]
+1

**Comment by raymondware** [comment]
You could place an image in your repo and reference it like this "![alt tag](https://raw.github.com/raymondware/awesome-courses/master/video-em.png)" I have forked your repo and placed an example there(https://github.com/raymondware/awesome-courses). Hope this helps!

**Comment by raymondware** [comment]
You could place an image in your repo and reference it like this  ```![alt tag](https://raw.github.com/raymondware/awesome-courses/master/video-em.png) ``` I have forked your repo and placed an example there(https://github.com/raymondware/awesome-courses). Hope this helps!

**Comment by raymondware** [comment]
Or you could just do this...

```<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f3a6.png" width="20" height="20" />```

**Comment by banderson623** [comment]
:+1: this is a good solution!

**Comment by prakhar1989** [comment]
Great idea! I'm travelling right now and I'll get to this in a couple of days. Thanks for tip :+1:

**Comment by prakhar1989** [comment]
As per @raymondware's suggestion, I've added emojis under the systems section in the [emoji](https://github.com/prakhar1989/awesome-courses/tree/emoji#systems) branch (alongwith a [legend](https://github.com/prakhar1989/awesome-courses/tree/emoji#legend)). 

It would be great if you all could  have a look and suggest improvements (if any). If this looks good, I'll go ahead and do the needful for other sections as well. Thanks! :grinning:
