### ISSUE TITLE
CS 473/573 - 404 not found

### ISSUE THREAD

**Issue by Ynjxsjmh** [prakhar1989/awesome-courses#303]
The server can not find the requested page:

web.engr.illinois.edu/~jeffe/teaching/algorithms/

**Comment by Ynjxsjmh** [comment]
I google it and find Jeff Erickson's Algorithm is on <http://jeffe.cs.illinois.edu/teaching/algorithms/>

`CS 473` and `CS 573` can also be easily found but it seems that university bilkent also have a course called [CS 473](http://cs.bilkent.edu.tr/~ozan.karsavuran/473/)

**Comment by spekulatius** [comment]
Fixed
