### ISSUE TITLE
Update Docs of README.md

### ISSUE THREAD

**Issue by priyankarpal** [prakhar1989/awesome-courses#338]
# Please update README.md docs, images are not showing.  
 
![Screenshot from 2023-01-13 21-50-28](https://user-images.githubusercontent.com/88102392/212368637-6bca6511-14e5-4c2e-9818-d960e55fdef3.png)
![Screenshot from 2023-01-13 21-50-20](https://user-images.githubusercontent.com/88102392/212368654-a500cbaf-dc3d-4b51-8a2b-1ce10af71de0.png)

**Comment by spekulatius** [comment]
Hey @priyankarpal 

yeah, that's something we are going to fix in the near future :+1: 

Cheers
