### ISSUE TITLE
Proposal to add courses: Algorithms by Jeff Erickson

### ISSUE THREAD

**Issue by yvan-sraka** [prakhar1989/awesome-courses#46]
What do you think of adding the teaching of Jeff Erickson in the algorithms section?

http://web.engr.illinois.edu/~jeffe/teaching/algorithms/

I think there is pretty awesome!

**Comment by prakhar1989** [comment]
It sure is! That's why it's already a part of the list. Check for CS473 by UIUC.

**Comment by yvan-sraka** [comment]
Oops, sorry.

Thanks!
